
language: node_js
node_js:
  - '8'
  # Please enable these matrix values after bug #228 is fixed
  #- '10'
  #- '12'

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

matrix:
  allow_failures:
    - os: windows
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.2
    - os: windows
      cache:
        - npm: false

install:
  # Adjust TravisCI build config to handle Windows Build timeouts caused by npm eperm errors.
  # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
  # https://travis-ci.community/t/eperm-operation-not-permitted-nodejs-electron/2571
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then travis_wait 30 npm install; else npm install; fi

script:
  - npm rebuild
  - npm run rebuild-leveldb
  - npm run lint
  - npm run build
  - npm run dist

deploy:
  provider: script
  script: npm run dist
  on:
    all_branches: true
  skip_cleanup: true
  file_glob: true
  file: "dist/Mapeo-darwin-x64/Installar_Mapeo*.dmg"
  api_key:
    secure: drFLl3ufKFIUyAdGDDtW8ddpEb75JydIpWobEMnIg+BlbsqdBree3AhuqkBJbO/gnyqs3XQp3tCMmsgCSj2hDVCNW0hsJ+lTzdLM0xpc85IRIYCAMf+x/4H2qIziwqNtxNI44Zuz2wVpwRmAC65mr8MqMsXqxe9ZO2udNdx/ofpkngvczHbcoYl2mhgmQPwtpV/YfVOWVtxTM0qF9zgfNdfRv/+tV44mU66ibXEgV3Lefco4TvmgAdlehwzD+tL36Idg1J4jgbnm+GK9iyhN3MO5RnUTT3mVK4gy2ovE/s3+tLSm98XdAo5+7NyqR8PwnLbuUHSpMX84jlp8vJ+vL2NvedQtCACu1LDB5pzc+vM7rf7K4B5N48VC8RYfMUUb/qtCylWd8QdqwSuSpxPV1beuWZOi7dwf03UAPjRhqGg+ATNisiyT8GnkhEg+z6AAV+dWz/dT1I6EbeotIOciy0HJ1wdCWbBve68W2aaDUSRsEOURi1YE/TYLZt77swjBHUbOrpz/udFp/Q93NH+RYlkh52VrCJ7K2KuLMLCSwsuR1IyK1e8kSCXZplph9YbZJzkk2D9hwV6SJX9vw+vmKBqz2gb02JNDmGxHVnvTZFw5U+1dzWAlMyqC+cqOBY0C668BFDJPZ/uJWDqoU+2FU0dLXx2XY7UBoup5pJUdFdw=
